services:
  mysql-driver:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_driver_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-team:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_team_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-track:
    image: mysql:latest
    ports:
      - 3309:3306
    volumes:
      - mysql_track_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mongo-results:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_results_data:/data/db
      
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
      
  driver-service:
    depends_on:
      - mysql-driver
    image: bricesey/driver-service:latest
    ports:
      - 8081:8081
    links:
      - mysql-driver
    volumes:
      - mysql_driver_data:/var/lib/mysql
    environment:
      MYSQL_DB_HOST: mysql-driver
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123

  team-service:
    depends_on:
      - mysql-team
    image: bricesey/team-service:latest
    ports:
      - 8082:8082
    links:
      - mysql-team
    volumes:
      - mysql_team_data:/var/lib/mysql
    environment:
      MYSQL_DB_HOST: mysql-team
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123

  track-service:
    depends_on:
      - mysql-track
    image: bricesey/track-service:latest
    ports:
      - 8083:8083
    links:
      - mysql-track
    volumes:
      - mysql_track_data:/var/lib/mysql
    environment:
      MYSQL_DB_HOST: mysql-track
      MYSQL_DB_PORT: 3306
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123

  results-service:
    depends_on:
      - mongo-results
    image: bricesey/results-service:latest
    ports:
      - 8084:8084
    links:
      - mongo-results
    volumes:
      - mongodb_results_data:/data/db
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-results

  api-gateway:
    depends_on:
      - driver-service
      - team-service
      - track-service
      - results-service
      - redis
    image: bricesey/api-gateway:latest
    ports:
      - 8088:8088
    links:
      - driver-service
      - team-service
      - track-service
      - results-service
    environment:
      DRIVER_SERVICE_BASEURL: driver-service:8081
      TEAM_SERVICE_BASEURL: team-service:8082
      TRACK_SERVICE_BASEURL: track-service:8083
      RESULT_SERVICE_BASEURL: results-service:8084


volumes:
  mongodb_results_data:
  mysql_driver_data:
  mysql_team_data:
  mysql_track_data:
  redis_data:
