server:
  port: 8088

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: http://${DRIVER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/drivers
            - Method=GET
          filters:
            - SetPath=/api/drivers
        - id: driver-service-create
          uri: http://${DRIVER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/drivers
            - Method=POST
          filters:
            - SetPath=/api/drivers
        - id: driver-service-edit
          uri: http://${DRIVER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/drivers/{id}
            - Method=PUT
          filters:
            - SetPath=/api/drivers/{id}
        - id: driver-service-delete
          uri: http://${DRIVER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/drivers/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/drivers/{id}