apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-driver-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-team-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-track-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-results-pvc
